/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class j_tool_snapshot_WindowSnapshot */

#ifndef _Included_j_tool_snapshot_WindowSnapshot
#define _Included_j_tool_snapshot_WindowSnapshot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     j_tool_snapshot_WindowSnapshot
 * Method:    snapshot
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_j_tool_snapshot_WindowSnapshot_snapshot
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
